package com.vectoramp.models;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/** Request for embedding text through a dataset and inserting the generated vectors. */
public class AddTextsRequest {
    private final List<String> texts;
    private final List<Object> ids;
    private final List<Map<String, Object>> metadata;

    /**
     * Creates an add-texts request.
     *
     * @param texts texts to embed and store as metadata.text
     * @param ids optional vector IDs (String or Number); missing IDs are generated by the client
     * @param metadata optional per-text metadata merged after metadata.text
     */
    public AddTextsRequest(List<String> texts, List<?> ids, List<Map<String, Object>> metadata) {
        this.texts = texts;
        this.ids = ids == null ? null : new ArrayList<>(ids);
        this.metadata = metadata;
    }

    /**
     * Creates a request for one text with a generated ID.
     * @param text text to add
     * @return add-texts request
     */
    public static AddTextsRequest of(String text) {
        return of(List.of(text));
    }

    /**
     * Creates a request for texts with generated IDs and no extra metadata.
     * @param texts texts to add
     * @return add-texts request
     */
    public static AddTextsRequest of(List<String> texts) {
        return new AddTextsRequest(texts, null, null);
    }

    /**
     * Creates a request for texts with optional string IDs and per-text metadata.
     * @param texts texts to add
     * @param ids optional string IDs
     * @param metadata optional metadata
     * @return add-texts request
     */
    public static AddTextsRequest of(List<String> texts, List<String> ids, List<Map<String, Object>> metadata) {
        return new AddTextsRequest(texts, ids, metadata);
    }

    /**
     * Creates a request for texts with numeric IDs that serialize as JSON numbers.
     * @param texts texts to add
     * @param ids numeric IDs (for example {@code Long}); serialized as JSON numbers on insert
     * @param metadata optional metadata
     * @return add-texts request
     */
    public static AddTextsRequest ofNumericIds(List<String> texts, List<? extends Number> ids, List<Map<String, Object>> metadata) {
        return new AddTextsRequest(texts, ids, metadata);
    }

    /**
     * @return texts
     */
    public List<String> getTexts() { return texts; }
    /**
     * The optional per-text vector IDs. Each entry is a {@link String} or {@link Number}; numeric
     * ids are inserted as JSON numbers. {@code null} when ids should be generated by the client.
     * @return ids
     */
    public List<Object> getIds() { return ids; }
    /**
     * @return metadata
     */
    public List<Map<String, Object>> getMetadata() { return metadata; }
}
