package com.vectoramp.models;

import java.util.List;
import java.util.Map;

/** Request for embedding text through a dataset and inserting the generated vectors. */
public class AddTextsRequest {
    private final List<String> texts;
    private final List<String> ids;
    private final List<Map<String, Object>> metadata;

    /**
     * Creates an add-texts request.
     *
     * @param texts texts to embed and store as metadata.text
     * @param ids optional vector IDs; missing IDs are generated by the client
     * @param metadata optional per-text metadata merged after metadata.text
     */
    public AddTextsRequest(List<String> texts, List<String> ids, List<Map<String, Object>> metadata) {
        this.texts = texts;
        this.ids = ids;
        this.metadata = metadata;
    }

    /**
     * Creates a request for one text with generated ID.
     * @param text text to add
     * @return add-texts request
     */
    public static AddTextsRequest of(String text) {
        return of(List.of(text));
    }

    /**
     * Creates a request for texts with generated IDs and no extra metadata.
     * @param texts texts to add
     * @return add-texts request
     */
    public static AddTextsRequest of(List<String> texts) {
        return new AddTextsRequest(texts, null, null);
    }

    /**
     * Creates a request for texts with optional IDs and per-text metadata.
     * @param texts texts to add
     * @param ids optional IDs
     * @param metadata optional metadata
     * @return add-texts request
     */
    public static AddTextsRequest of(List<String> texts, List<String> ids, List<Map<String, Object>> metadata) {
        return new AddTextsRequest(texts, ids, metadata);
    }

    /**
     * @return texts
     */
    public List<String> getTexts() { return texts; }
    /**
     * @return ids
     */
    public List<String> getIds() { return ids; }
    /**
     * @return metadata
     */
    public List<Map<String, Object>> getMetadata() { return metadata; }
}
